#############################################################################
# Makefile for building: OpenGL
# Generated by qmake (3.0) (Qt 5.3.2)
# Project:  PhysicsEngine.pro
# Template: app
# Command: /home/louis/Qt/5.3/gcc_64/bin/qmake -spec linux-clang CONFIG+=debug -o Makefile PhysicsEngine.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DNGL_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -I/usr/local/include/SDL2 -D_REENTRANT -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I../../../../../Qt/5.3/gcc_64/mkspecs/linux-clang -I. -I../../../../../Qt/5.3/gcc_64/include -I../../../../../Qt/5.3/gcc_64/include/QtGui -I../../../../../Qt/5.3/gcc_64/include/QtCore -I.
LINK          = clang++
LFLAGS        = -ccc-gcc-name g++ -Wl,-rpath,/home/louis/Qt/5.3/gcc_64 -Wl,-rpath,/home/louis/Qt/5.3/gcc_64/lib
LIBS          = $(SUBLIBS) -L/usr/local/lib -Wl,-rpath,/usr/local/lib -lSDL2 -lGLU -lglut -L/home/louis/Qt/5.3/gcc_64/lib -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/louis/Qt/5.3/gcc_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/shelf.cpp 
OBJECTS       = main.o \
		shelf.o
DIST          = ../../../../../Qt/5.3/gcc_64/mkspecs/features/spec_pre.prf \
		../../../../../Qt/5.3/gcc_64/mkspecs/common/shell-unix.conf \
		../../../../../Qt/5.3/gcc_64/mkspecs/common/unix.conf \
		../../../../../Qt/5.3/gcc_64/mkspecs/common/linux.conf \
		../../../../../Qt/5.3/gcc_64/mkspecs/common/gcc-base.conf \
		../../../../../Qt/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../../../Qt/5.3/gcc_64/mkspecs/common/clang.conf \
		../../../../../Qt/5.3/gcc_64/mkspecs/qconfig.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/features/qt_functions.prf \
		../../../../../Qt/5.3/gcc_64/mkspecs/features/qt_config.prf \
		../../../../../Qt/5.3/gcc_64/mkspecs/linux-clang/qmake.conf \
		../../../../../Qt/5.3/gcc_64/mkspecs/features/spec_post.prf \
		../../../../../.qmake.cache \
		../../../../../Qt/5.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../../../Qt/5.3/gcc_64/mkspecs/features/default_pre.prf \
		../../../../../Qt/5.3/gcc_64/mkspecs/features/resolve_config.prf \
		../../../../../Qt/5.3/gcc_64/mkspecs/features/default_post.prf \
		../../../../../Qt/5.3/gcc_64/mkspecs/features/warn_on.prf \
		../../../../../Qt/5.3/gcc_64/mkspecs/features/qt.prf \
		../../../../../Qt/5.3/gcc_64/mkspecs/features/resources.prf \
		../../../../../Qt/5.3/gcc_64/mkspecs/features/moc.prf \
		../../../../../Qt/5.3/gcc_64/mkspecs/features/unix/opengl.prf \
		../../../../../Qt/5.3/gcc_64/mkspecs/features/unix/thread.prf \
		../../../../../Qt/5.3/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../../../Qt/5.3/gcc_64/mkspecs/features/exceptions.prf \
		../../../../../Qt/5.3/gcc_64/mkspecs/features/yacc.prf \
		../../../../../Qt/5.3/gcc_64/mkspecs/features/lex.prf \
		PhysicsEngine.pro src/main.cpp \
		src/shelf.cpp
QMAKE_TARGET  = OpenGL
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = OpenGL


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: PhysicsEngine.pro ../../../../../.qmake.cache ../../../../../Qt/5.3/gcc_64/mkspecs/linux-clang/qmake.conf ../../../../../Qt/5.3/gcc_64/mkspecs/features/spec_pre.prf \
		../../../../../Qt/5.3/gcc_64/mkspecs/common/shell-unix.conf \
		../../../../../Qt/5.3/gcc_64/mkspecs/common/unix.conf \
		../../../../../Qt/5.3/gcc_64/mkspecs/common/linux.conf \
		../../../../../Qt/5.3/gcc_64/mkspecs/common/gcc-base.conf \
		../../../../../Qt/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../../../Qt/5.3/gcc_64/mkspecs/common/clang.conf \
		../../../../../Qt/5.3/gcc_64/mkspecs/qconfig.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../../Qt/5.3/gcc_64/mkspecs/features/qt_functions.prf \
		../../../../../Qt/5.3/gcc_64/mkspecs/features/qt_config.prf \
		../../../../../Qt/5.3/gcc_64/mkspecs/linux-clang/qmake.conf \
		../../../../../Qt/5.3/gcc_64/mkspecs/features/spec_post.prf \
		../../../../../.qmake.cache \
		../../../../../Qt/5.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../../../Qt/5.3/gcc_64/mkspecs/features/default_pre.prf \
		../../../../../Qt/5.3/gcc_64/mkspecs/features/resolve_config.prf \
		../../../../../Qt/5.3/gcc_64/mkspecs/features/default_post.prf \
		../../../../../Qt/5.3/gcc_64/mkspecs/features/warn_on.prf \
		../../../../../Qt/5.3/gcc_64/mkspecs/features/qt.prf \
		../../../../../Qt/5.3/gcc_64/mkspecs/features/resources.prf \
		../../../../../Qt/5.3/gcc_64/mkspecs/features/moc.prf \
		../../../../../Qt/5.3/gcc_64/mkspecs/features/unix/opengl.prf \
		../../../../../Qt/5.3/gcc_64/mkspecs/features/unix/thread.prf \
		../../../../../Qt/5.3/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../../../Qt/5.3/gcc_64/mkspecs/features/exceptions.prf \
		../../../../../Qt/5.3/gcc_64/mkspecs/features/yacc.prf \
		../../../../../Qt/5.3/gcc_64/mkspecs/features/lex.prf \
		PhysicsEngine.pro \
		/home/louis/Qt/5.3/gcc_64/lib/libQt5Gui.prl \
		/home/louis/Qt/5.3/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -spec linux-clang CONFIG+=debug -o Makefile PhysicsEngine.pro
../../../../../Qt/5.3/gcc_64/mkspecs/features/spec_pre.prf:
../../../../../Qt/5.3/gcc_64/mkspecs/common/shell-unix.conf:
../../../../../Qt/5.3/gcc_64/mkspecs/common/unix.conf:
../../../../../Qt/5.3/gcc_64/mkspecs/common/linux.conf:
../../../../../Qt/5.3/gcc_64/mkspecs/common/gcc-base.conf:
../../../../../Qt/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../../../../Qt/5.3/gcc_64/mkspecs/common/clang.conf:
../../../../../Qt/5.3/gcc_64/mkspecs/qconfig.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../../Qt/5.3/gcc_64/mkspecs/features/qt_functions.prf:
../../../../../Qt/5.3/gcc_64/mkspecs/features/qt_config.prf:
../../../../../Qt/5.3/gcc_64/mkspecs/linux-clang/qmake.conf:
../../../../../Qt/5.3/gcc_64/mkspecs/features/spec_post.prf:
../../../../../.qmake.cache:
../../../../../Qt/5.3/gcc_64/mkspecs/features/exclusive_builds.prf:
../../../../../Qt/5.3/gcc_64/mkspecs/features/default_pre.prf:
../../../../../Qt/5.3/gcc_64/mkspecs/features/resolve_config.prf:
../../../../../Qt/5.3/gcc_64/mkspecs/features/default_post.prf:
../../../../../Qt/5.3/gcc_64/mkspecs/features/warn_on.prf:
../../../../../Qt/5.3/gcc_64/mkspecs/features/qt.prf:
../../../../../Qt/5.3/gcc_64/mkspecs/features/resources.prf:
../../../../../Qt/5.3/gcc_64/mkspecs/features/moc.prf:
../../../../../Qt/5.3/gcc_64/mkspecs/features/unix/opengl.prf:
../../../../../Qt/5.3/gcc_64/mkspecs/features/unix/thread.prf:
../../../../../Qt/5.3/gcc_64/mkspecs/features/testcase_targets.prf:
../../../../../Qt/5.3/gcc_64/mkspecs/features/exceptions.prf:
../../../../../Qt/5.3/gcc_64/mkspecs/features/yacc.prf:
../../../../../Qt/5.3/gcc_64/mkspecs/features/lex.prf:
PhysicsEngine.pro:
/home/louis/Qt/5.3/gcc_64/lib/libQt5Gui.prl:
/home/louis/Qt/5.3/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-clang CONFIG+=debug -o Makefile PhysicsEngine.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/OpenGL1.0.0 || mkdir -p .tmp/OpenGL1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/OpenGL1.0.0/ && $(COPY_FILE) --parents header/ball.h header/scene.h header/shelf.h header/window.h .tmp/OpenGL1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/shelf.cpp .tmp/OpenGL1.0.0/ && (cd `dirname .tmp/OpenGL1.0.0` && $(TAR) OpenGL1.0.0.tar OpenGL1.0.0 && $(COMPRESS) OpenGL1.0.0.tar) && $(MOVE) `dirname .tmp/OpenGL1.0.0`/OpenGL1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/OpenGL1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: src/main.cpp header/scene.h \
		header/ball.h \
		src/ball.cpp \
		header/shelf.h \
		header/window.h \
		src/window.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

shelf.o: src/shelf.cpp header/shelf.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o shelf.o src/shelf.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

